---
# Repository configuration for DNF, Yum, and COPR

- name: Install the RPMFusion repo packages
  ansible.builtin.dnf:
    state: present
    disable_gpg_check: true
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_current }}.noarch.rpm"
      - "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_current }}.noarch.rpm"

- name: Enable COPR repositories
  community.general.copr:
    name: "{{ item }}"
    state: enabled
  loop: "{{ repositories_copr }}"

- name: Add third-party Yum repositories
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: true
    gpgcheck: "{{ item.gpgcheck | default(true) }}"
    repo_gpgcheck: "{{ item.repo_gpgcheck | default(false) }}"
    gpgkey: "{{ item.gpgkey }}"
    sslverify: "{{ item.sslverify | default(omit) }}"
    sslcacert: "{{ item.sslcacert | default(omit) }}"
    metadata_expire: "{{ item.metadata_expire | default(omit) }}"
  loop: "{{ repositories_yum }}"
